apiVersion: v1
kind: Service
metadata:
  name: mcp-service
  namespace: multiagent-assistant
  labels:
    app: mcp-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: mcp-service
