apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: multiagent-assistant
  labels:
    app: apisix
spec:
  selector:
    app: apisix
  ports:
  - name: http
    port: 9080
    targetPort: 9080
