apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: multiagent-assistant
type: Opaque
stringData:
  POSTGRES_USER: "appuser"
  POSTGRES_PASSWORD: "apppass"
  POSTGRES_DB: "appdb"
